"""Keep internal agent-process files and names out of the public tree."""

import re
import subprocess
from pathlib import Path

import pytest

ROOT = Path(__file__).parents[1]
# Files that must name internal paths to keep them out, plus a generated lockfile.
SKIPPED = {
    ".gitignore",  # lists internal paths so git ignores them
    ".dockerignore",  # lists internal paths so image builds leave them out
    "uv.lock",  # generated by uv; package names are not ours to edit
}
# A line carrying this marker is exempt, so the term list below can live as data.
ALLOW_MARKER = "leakguard: allow"
INTERNAL_PATH = re.compile(r"superpowers|^docs/(plans|specs)/")  # leakguard: allow
# Matched as case-insensitive substrings, so joined names like FooBar_review also fail.
# Keep in sync with the global leak guard.
INTERNAL_TERMS = (
    "kestrel", "harrier", "omnara", "apiana", "daedalus", "seo-yun",  # leakguard: allow
    "odette", "gideon", "holloway", "marlowe", "gearnoccio", "linkwell",  # leakguard: allow
    "hyperbots", "gabe-factory", "agentskit", "superpowers",  # leakguard: allow
    "subagent-driven", "everything-claude-code", "estaleiro",  # leakguard: allow
    "kestrel-reviews", "agent-memory", "gate-debrief", "submission-gate",  # leakguard: allow
    "crew-new-hire", "pr-risk-map", "skill-doctor", "voice-profile-gabe",  # leakguard: allow
    "nuclear-review", "/users/gava", "gabe_gate",  # leakguard: allow
)  # fmt: skip
INTERNAL_TEXT = re.compile("|".join(map(re.escape, INTERNAL_TERMS)), re.IGNORECASE)


def _tracked_files() -> list[str]:
    try:
        result = subprocess.run(
            ["git", "ls-files", "-z"], cwd=ROOT, capture_output=True, check=False
        )
    except FileNotFoundError:
        pytest.skip("git is not installed")
    if result.returncode != 0:
        pytest.skip("not a git checkout")
    return [p for p in result.stdout.decode("utf-8").split("\0") if p]


def test_no_internal_planning_paths_are_tracked():
    assert [p for p in _tracked_files() if INTERNAL_PATH.search(p)] == []


def test_tracked_text_files_do_not_name_internal_process():
    findings = []
    for rel in _tracked_files():
        if rel in SKIPPED:
            continue
        path = ROOT / rel
        if not path.is_file():
            continue
        data = path.read_bytes()
        if b"\0" in data:  # binary file
            continue
        try:
            text = data.decode("utf-8")
        except UnicodeDecodeError:  # not text
            continue
        for number, line in enumerate(text.splitlines(), start=1):
            if ALLOW_MARKER not in line and INTERNAL_TEXT.search(line):
                findings.append(f"{rel}:{number}")
    assert findings == []
